[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ribo-remover"
version = "0.1.0"
requires-python = '>=3.9'

[project.scripts]
ribo-remover = "ribo_remover.ribo_remover:main"
